import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { createLogger } from './logger.js';
import type { StorageAdapter } from './storage/adapter.js';
import type { RuleSuggestion, AutoClawConfig } from './types.js';

const logger = createLogger('rule-applier');

/**
 * Auto-approve rules with confidence >= threshold
 * THRESHOLD = 0.70 (CRITICAL — do not change)
 */
export async function autoApproveHighConfidenceRules(
  storage: StorageAdapter,
  config: AutoClawConfig
): Promise<RuleSuggestion[]> {
  const threshold = config.autoApproveThreshold; // 0.70
  const pendingRules = await storage.getRules({ status: 'PENDING' });

  const approved: RuleSuggestion[] = [];

  for (const rule of pendingRules) {
    if (rule.confidence >= threshold) {
      await storage.updateRule(rule.id, { status: 'APPROVED' });
      approved.push({ ...rule, status: 'APPROVED' });
      logger.info(`Auto-approved: "${rule.title}" (confidence: ${rule.confidence})`);
    }
  }

  logger.info(`Auto-approved ${approved.length}/${pendingRules.length} pending rules (threshold: ${threshold})`);
  return approved;
}

/**
 * Write a single rule to disk in the target directories
 */
export function applyApprovedRule(
  rule: RuleSuggestion,
  targetDirs: string[],
  cwd: string = process.cwd()
): string[] {
  const fileName =
    rule.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') + '.md';

  const writtenPaths: string[] = [];

  for (const dir of targetDirs) {
    const fullDir = join(cwd, dir);
    const filePath = join(fullDir, fileName);

    mkdirSync(fullDir, { recursive: true });

    const content = `# ${rule.title}\n\n${rule.content}\n\n<!-- Generated by AutoClaw | confidence: ${rule.confidence} | category: ${rule.category} -->\n`;
    writeFileSync(filePath, content, 'utf-8');
    writtenPaths.push(filePath);

    logger.info(`Written rule to ${filePath}`);
  }

  return writtenPaths;
}

/**
 * Apply all approved rules to disk and update their status
 */
export async function applyAllPendingRules(
  storage: StorageAdapter,
  config: AutoClawConfig,
  cwd: string = process.cwd()
): Promise<{ applied: number; skipped: number }> {
  const approvedRules = await storage.getRules({ status: 'APPROVED' });

  let applied = 0;
  let skipped = 0;

  for (const rule of approvedRules) {
    try {
      const paths = applyApprovedRule(rule, config.targetDirs, cwd);

      const now = new Date().toISOString();
      await storage.updateRule(rule.id, { status: 'APPLIED', appliedAt: now });

      // Save version
      await storage.saveRuleVersion({
        ruleId: rule.id,
        version: 1,
        content: rule.content,
        createdAt: now,
      });

      applied++;
      logger.info(`Applied rule: "${rule.title}" to ${paths.length} directories`);
    } catch (error) {
      skipped++;
      logger.error(`Failed to apply rule: "${rule.title}"`, error);
    }
  }

  logger.info(`Applied ${applied} rules, skipped ${skipped}`);
  return { applied, skipped };
}

