import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { createLogger } from './logger.js';
import { readStarterKit, applyStarterKit } from './starter-kit.js';
import type { StarterKit } from './starter-kit.js';
import type { StorageAdapter } from './storage/adapter.js';
import type { StarterKitSnapshot, StarterKitFile } from './types.js';

const logger = createLogger('starter-kit-distributor');

export interface DistributionResult {
  applied: string[];
  skipped: string[];
  errors: string[];
  claudeMdGenerated: boolean;
  huskyInstalled: boolean;
  snapshotSaved: boolean;
}

/**
 * Distribute a starter kit to a target project directory.
 * Applies rules, generates CLAUDE.md, installs Husky hook, and saves snapshot.
 */
export async function distributeStarterKit(
  kitPath: string,
  targetDir: string,
  storage: StorageAdapter,
  options: {
    projectName?: string;
    overwrite?: boolean;
    dryRun?: boolean;
    skipHusky?: boolean;
  } = {}
): Promise<DistributionResult> {
  const projectName = options.projectName ?? inferProjectName(targetDir);

  logger.info(`Distributing starter kit to "${projectName}" at ${targetDir}`);

  const kit = readStarterKit(kitPath);

  const applyResult = applyStarterKit(kit, targetDir, {
    overwrite: options.overwrite,
    dryRun: options.dryRun,
  });

  const result: DistributionResult = {
    ...applyResult,
    claudeMdGenerated: false,
    huskyInstalled: false,
    snapshotSaved: false,
  };

  if (options.dryRun) {
    return result;
  }

  // Generate CLAUDE.md adapted with project name
  try {
    result.claudeMdGenerated = generateClaudeMd(kit, targetDir, projectName);
  } catch (err) {
    result.errors.push(
      `CLAUDE.md generation failed: ${err instanceof Error ? err.message : String(err)}`
    );
  }

  // Install Husky post-commit hook
  if (!options.skipHusky) {
    try {
      result.huskyInstalled = installHuskyHook(targetDir);
    } catch (err) {
      result.errors.push(
        `Husky hook failed: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  // Save snapshot to storage
  try {
    const snapshot = buildSnapshot(kit, kitPath);
    await storage.saveSnapshot(snapshot);
    result.snapshotSaved = true;
  } catch (err) {
    result.errors.push(
      `Snapshot save failed: ${err instanceof Error ? err.message : String(err)}`
    );
  }

  return result;
}

/**
 * Infer project name from package.json, falling back to directory name.
 */
export function inferProjectName(targetDir: string): string {
  const pkgPath = join(targetDir, 'package.json');
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as Record<string, unknown>;
      if (typeof pkg.name === 'string' && pkg.name) return pkg.name;
    } catch {
      /* ignore parse errors */
    }
  }
  return targetDir.split('/').filter(Boolean).pop() ?? 'project';
}

function generateClaudeMd(kit: StarterKit, targetDir: string, projectName: string): boolean {
  const templatePath = join(kit.basePath, 'CLAUDE.md');

  if (!existsSync(templatePath)) {
    const content = [
      `# CLAUDE.md — ${projectName}`,
      '',
      `> Auto-generated by AutoClaw starter kit "${kit.manifest.name}" v${kit.manifest.version}`,
      '',
      '## Rules',
      '',
      'See .claude/rules/ for project-specific rules.',
      '',
    ].join('\n');
    writeFileSync(join(targetDir, 'CLAUDE.md'), content, 'utf-8');
    return true;
  }

  let content = readFileSync(templatePath, 'utf-8');
  content = content.replace(/\[ADAPTER\]/g, projectName);
  content = content.replace(/\[PROJECT_NAME\]/g, projectName);
  content = content.replace(/\[KIT_VERSION\]/g, kit.manifest.version);
  writeFileSync(join(targetDir, 'CLAUDE.md'), content, 'utf-8');
  return true;
}

function installHuskyHook(targetDir: string): boolean {
  // Check if Husky is available before writing the hook
  try {
    execSync('npx husky --version', { cwd: targetDir, stdio: 'pipe' });
  } catch {
    logger.info('Husky not available — hook installation skipped');
    return false;
  }

  const huskyDir = join(targetDir, '.husky');
  mkdirSync(huskyDir, { recursive: true });

  const hookPath = join(huskyDir, 'post-commit');
  const autoclaWLine = 'npx autoclaw run --since="last commit" --quiet 2>/dev/null || true';

  if (existsSync(hookPath)) {
    const existing = readFileSync(hookPath, 'utf-8');
    if (existing.includes('autoclaw')) {
      logger.info('Husky post-commit hook already contains autoclaw — skipping');
      return true;
    }
    // Append to existing hook without overwriting user content
    const separator = existing.endsWith('\n') ? '' : '\n';
    writeFileSync(hookPath, `${existing}${separator}# AutoClaw post-commit hook\n${autoclaWLine}\n`, { mode: 0o755 });
    return true;
  }

  const hookContent = [
    '#!/bin/sh',
    '# AutoClaw post-commit hook',
    autoclaWLine,
    '',
  ].join('\n');

  writeFileSync(hookPath, hookContent, { mode: 0o755 });
  return true;
}

function buildSnapshot(kit: StarterKit, kitPath: string): StarterKitSnapshot {
  const files: StarterKitFile[] = kit.rules.map(({ rule, content }) => ({
    relativePath: rule.path,
    checksum: createHash('sha256').update(content).digest('hex'),
    size: Buffer.byteLength(content, 'utf-8'),
    category: 'rule' as const,
  }));

  return {
    version: kit.manifest.version,
    capturedAt: new Date().toISOString(),
    starterKitPath: kitPath,
    files,
    totalFiles: files.length,
  };
}

